### ISSUE TITLE
add an input

### ISSUE THREAD

**Issue by jairo-futurasmus** [razvanstanga/node-red-contrib-onvif#1]
I think it would be interesting to add an entry to this node so that it can be triggered with any event.

**Comment by razvanstanga** [comment]
That is the plan.

**Comment by jairo-futurasmus** [comment]
:) great, take a look at the [pullrequest](https://github.com/razvanstanga/node-red-contrib-onvif/pull/2)

**Comment by razvanstanga** [comment]
added
