### ISSUE TITLE
PTZ Function for light on/off

### ISSUE THREAD

**Issue by commander-bln** [razvanstanga/node-red-contrib-onvif#5]
i use your node to get some Snapshots of IP ONVIF Cameras (exp.Pond camera AP-W28316)

one of them have IR Led and Light to switch on and off over the webinterface. They used the PTZ function

The two arrow keys UP / DOWN serve to switch the white
light or the IR light on / off and to control the light intensity in
several stages. The LEFT arrow key switches the camera to
infrared (IR) mode and between the three operating modes:
1. IR-LED manual / 2. IR-LED time-controlled / 3. IR-LED
automatic *. The RIGHT arrow key switches the camera to
white light mode and between the three operating modes: 1.
White light manual / 2. White light time-controlled / 3. White
light automatic *
All other buttons have no control function! 

**my question: is this possible with your node? and if yes how?
oder is there any plan to implement this function? #** #

**Comment by razvanstanga** [comment]
I don't have any plans for this.

**Comment by commander-bln** [comment]
Thanx, it works, after i know to install the Beta...manuellyVon Unterwegs gesendet.
-------- Ursprüngliche Nachricht --------Von: Razvan Stanga ***@***.***> Datum: 21.03.22  13:03  (GMT+01:00) An: razvanstanga/node-red-contrib-onvif ***@***.***> Cc: commander-bln ***@***.***>, Author ***@***.***> Betreff: Re: [razvanstanga/node-red-contrib-onvif] PTZ Function for light on/off (#5) 
I don't have any plans for this.
